name: Documentation
description: Builds Docusaurus site and publishes it to Github Pages
inputs:
  GITHUB_TOKEN:
    description: Github token, needed for pushing the docs to the repo
    required: true

runs:
  using: composite

  steps:
    - name: 🔨 Build native-base-components:docs
      shell: bash
      run: yarn build:apps:docs
      
    - name: 🚀 Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./apps/docs/build
        token: ${{ inputs.GITHUB_TOKEN }}
