name: Quality Gate
description: Ensures the continued quality of the code

runs:
  using: composite

  steps:
    - name: 🌱 Initialize CodeQL
      uses: github/codeql-action/init@v2
    - name: 🧼 Clean Old Build Artifacts
      shell: bash
      run: yarn clean
    - name: 🧹 Lint Code
      shell: bash
      run: yarn lint
    - name: 🔨 Build Code
      shell: bash
      run: yarn build
    - name: 🧪 Run Unit Tests
      shell: bash
      run: yarn test
    - name: 🔬 Analyze Code
      uses: github/codeql-action/analyze@v2    